wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.14.0
    framework: keras
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.9.13
    start_time: 1679611095.163338
    t:
      1:
      - 2
      - 3
      - 5
      - 53
      - 55
      2:
      - 2
      - 3
      - 5
      - 53
      - 55
      3:
      - 16
      - 23
      4: 3.9.13
      5: 0.14.0
      8:
      - 1
      - 5
architecture:
  desc: null
  value: CNN
dataset:
  desc: null
  value: PROTON DATA
epochs:
  desc: null
  value: 10
learning_rate:
  desc: null
  value: 0.02
